kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      containers:
        - name: postgres
          image: stanleywxc/postgres:12.3
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: 100m
          volumeMounts:
            - name: data-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data-volume
          hostPath:
            # directory location on host
            path: /Users/stanley/tmp/data/postgres/data
            type: Directory